[env]
TERM = "alacritty"

[font]
size = 10


[font.normal]
# family = "HackGen35 Console NF"
family = "Moralerspace Argon NF"
style = "Regular"

[scrolling]
history = 10000
multiplier = 5

[shell]
program = "/Windows/System32/wsl.exe ~"

[window]
opacity = 0.98
startup_mode = "Maximized"
title = "Starbucks"
