[env]
TERM = "alacritty"

[font]
size = 11.5


[font.normal]
# family = "FiraCode Nerd Font"
family = "HackGen Console NF"
style = "Regular"

[scrolling]
history = 10000
multiplier = 5

[shell]
program = "/Windows/System32/wsl.exe ~"

[window]
opacity = 0.98
startup_mode = "Maximized"
title = "Starbucks"
