[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "HackGen Console NF"
style = "Bold"

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[scrolling]
history = 10000

[shell]
program = "/Windows/System32/wsl.exe ~"

[window]
opacity = 0.95
startup_mode = "Maximized"
title = "Alacritty"

# [window.dimentions]
# columns = 220
# lines = 75
