[env]
TERM = "alacritty"

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 5

[window]
opacity = 0.98
startup_mode = "Maximized"
title = "Starbucks"
